//
//  InitialScreenConfigurator.swift
//  marvelMovies
//
//  Created by Franco Marquez on 23/08/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the StartApps CleanSwift Xcode Templates. V2.0
//  By Gabriel Lanata (http://StartApps.pe) with credit to http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension InitialScreenViewController {

    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(segue: segue)
    }

    override func awakeFromNib() {
        super.awakeFromNib()
        InitialScreenConfigurator.configure(viewController: self)
    }

    static func instantiate() -> InitialScreenViewController {
        return InitialScreenViewController()
    }

}

class InitialScreenConfigurator {

    // MARK: - Configuration

    static func configure(viewController: InitialScreenViewController) {

        let presenter = InitialScreenPresenter()
        presenter.viewController = viewController

        let interactor = InitialScreenInteractor()
        interactor.presenter = presenter

        let router = InitialScreenRouter()
        router.viewController = viewController
        router.interactor = interactor

        viewController.interactor = interactor
        viewController.router = router
    }

}
