//
//  HomeInteractor.swift
//  marvelMovies
//
//  Created by Franco Marquez on 23/08/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the StartApps CleanSwift Xcode Templates. V2.0
//  By Gabriel Lanata (http://StartApps.pe) with credit to http://clean-swift.com
//

import Foundation

class HomeInteractor {

    var presenter: HomePresenter?

    // MARK: - Object variables

    // var loadAction: loadAction!

    // MARK: - Business logic

    func doinitialLoad(request: HomeScene.initialLoad.Request) {
        // NOTE: Pass the result to the Presenter
        do {
            CharactersWebService.shared.getCharacters{ response in
                
                switch response.result{
                    
                case .success(let data):
                    
                    do {
                        
                        let finalData = try JSONDecoder().decode(ResponseCharacters.self, from: data)
                        self.presenter?.presentinitialLoad(response: HomeScene.initialLoad.Response(characterResponse: finalData))
                        
                    } catch{
                        self.presenter?.presentAlertError(response: HomeScene.AlertError.Response(error: error))
                    }
                    
                case.failure(let error):
                    self.presenter?.presentAlertError(response: HomeScene.AlertError.Response(error: error))
                }
                
            }
            
        } catch {
            presenter?.presentAlertError(response: HomeScene.AlertError.Response(
                error: error
            ))
        }
    }

}
