//
//  HeroDetailConfigurator.swift
//  marvelMovies
//
//  Created by Franco Marquez on 28/08/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the StartApps CleanSwift Xcode Templates. V2.0
//  By Gabriel Lanata (http://StartApps.pe) with credit to http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension HeroDetailViewController {

    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(segue: segue)
    }

    override func awakeFromNib() {
        super.awakeFromNib()
        HeroDetailConfigurator.configure(viewController: self)
    }

    static func instantiate(heroId: Int) -> HeroDetailViewController {
        let vc = HeroDetailViewController()
        vc.heroId = heroId
        return vc
    }

}

class HeroDetailConfigurator {

    // MARK: - Configuration

    static func configure(viewController: HeroDetailViewController) {

        let presenter = HeroDetailPresenter()
        presenter.viewController = viewController

        let interactor = HeroDetailInteractor()
        interactor.presenter = presenter

        let router = HeroDetailRouter()
        router.viewController = viewController
        router.interactor = interactor

        viewController.interactor = interactor
        viewController.router = router
    }

}
