//
//  HeroDetailPresenter.swift
//  marvelMovies
//
//  Created by Franco Marquez on 28/08/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the StartApps CleanSwift Xcode Templates. V2.0
//  By Gabriel Lanata (http://StartApps.pe) with credit to http://clean-swift.com
//

import Foundation

class HeroDetailPresenter {

    weak var viewController: HeroDetailViewController?

    // MARK: - Presentation logic
    
    func presentInitialDataLoad(response: HeroDetailScene.InitialDataLoad.Response) {
        // NOTE: Format the response from the Interactor and pass the result back to the View Controller
        // NOTE: Remember to use workers if complex processing is required
        
        guard let hero = response.heroResponse.data.results.first else { return }
        
        guard let Url = URL(string: hero.thumbnail.path + "." +  hero.thumbnail.thumbnailExtension.rawValue) else { return }
        
        let heroData = HeroDetailScene.InitialDataLoad.ViewModel.heroInfo(heroName: hero.name,
                                                                          heroDescription: hero.description,
                                                                          heroPhotoUrl: Url)
        
        viewController?.displayInitialDataLoad(viewModel: heroData)
    }
    
    func presentAlertError(response: HeroDetailScene.AlertError.Response) {
        viewController?.displayAlertError(viewModel: HeroDetailScene.AlertError.ViewModel(
            message: response.error.localizedDescription
        ))
    }

}
