//
//  HeroDetailModels.swift
//  marvelMovies
//
//  Created by Franco Marquez on 28/08/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the StartApps CleanSwift Xcode Templates. V2.0
//  By Gabriel Lanata (http://StartApps.pe) with credit to http://clean-swift.com
//

import Foundation

enum HeroDetailScene {
    
    enum InitialDataLoad {
        
        struct Request {
            var heroId: Int
        }
        struct Response {
            
            var heroResponse : ResponseCharacters
            
        }
        struct ViewModel {
            struct heroInfo{
                var heroName: String
                var heroDescription: String
                var heroPhotoUrl: URL
            }
        }
        
    }
    
    enum AlertError {
        
        struct Response {
            let error: Error
        }
        struct ViewModel {
            let message: String
        }
        
    }

}
