//
//  ComicDetailInteractor.swift
//  marvelMovies
//
//  Created by Franco Marquez on 28/08/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the StartApps CleanSwift Xcode Templates. V2.0
//  By Gabriel Lanata (http://StartApps.pe) with credit to http://clean-swift.com
//

import Foundation

class ComicDetailInteractor {

    var presenter: ComicDetailPresenter?

    // MARK: - Object variables

    // var loadAction: loadAction!

    // MARK: - Business logic

    func doInitialLoadComicDetail(request: ComicDetailScene.InitialLoadComicDetail.Request) {
        // NOTE: Pass the result to the Presenter
        
        ComicsWebService.shared.getComicById(comicId: request.comicId) { response in
            switch response.result{
                
            case .success(let data):
                
                do {
                    let finalData = try JSONDecoder().decode(ComicsResponse.self, from: data)
                    
                    self.presenter?.presentInitialLoadComicDetail(response: ComicDetailScene.InitialLoadComicDetail.Response(comicRepsonse: finalData))
                    
                } catch {
                    self.presenter?.presentAlertError(response: ComicDetailScene.AlertError.Response(error: error))
                }
                
            case .failure(let error):
                self.presenter?.presentAlertError(response: ComicDetailScene.AlertError.Response(error: error))
            }
        }
        
    }

}
