//
//  ComicDetailConfigurator.swift
//  marvelMovies
//
//  Created by Franco Marquez on 28/08/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the StartApps CleanSwift Xcode Templates. V2.0
//  By Gabriel Lanata (http://StartApps.pe) with credit to http://clean-swift.com
//

import UIKit

// MARK: - Connect View, Interactor, and Presenter

extension ComicDetailViewController {

    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        router.passDataToNextScene(segue: segue)
    }

    override func awakeFromNib() {
        super.awakeFromNib()
        ComicDetailConfigurator.configure(viewController: self)
    }

    static func instantiate(comicId: Int) -> ComicDetailViewController {
        let vc = ComicDetailViewController()
        vc.comicId = comicId
        ComicDetailConfigurator.configure(viewController: vc)
        return vc
    }

}

class ComicDetailConfigurator {

    // MARK: - Configuration

    static func configure(viewController: ComicDetailViewController) {

        let presenter = ComicDetailPresenter()
        presenter.viewController = viewController

        let interactor = ComicDetailInteractor()
        interactor.presenter = presenter

        let router = ComicDetailRouter()
        router.viewController = viewController
        router.interactor = interactor

        viewController.interactor = interactor
        viewController.router = router
    }

}
