//
//  ComicDetailPresenter.swift
//  marvelMovies
//
//  Created by Franco Marquez on 28/08/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the StartApps CleanSwift Xcode Templates. V2.0
//  By Gabriel Lanata (http://StartApps.pe) with credit to http://clean-swift.com
//

import Foundation

class ComicDetailPresenter {

    weak var viewController: ComicDetailViewController?

    // MARK: - Presentation logic
    
    func presentInitialLoadComicDetail(response: ComicDetailScene.InitialLoadComicDetail.Response) {
        // NOTE: Format the response from the Interactor and pass the result back to the View Controller
        // NOTE: Remember to use workers if complex processing is required
        
        guard let comic = response.comicRepsonse.data.results.first else {
            viewController?.displayAlertError(viewModel: ComicDetailScene.AlertError.ViewModel(message: "No comic"))
            return
        }
        
        guard let photoURL = URL(string: comic.thumbnail.path + "." + comic.thumbnail.thumbnailExtension.rawValue) else {
            viewController?.displayAlertError(viewModel: ComicDetailScene.AlertError.ViewModel(message: "Bad comic url"))
            return
        }
        
        viewController?.displayInitialLoadComicDetail(viewModel: ComicDetailScene.InitialLoadComicDetail.ViewModel(comicTitle: comic.title,
                                                                                                                   comicPhotoURL: photoURL,
                                                                                                                   comicDescription: comic.description ?? ""))
        
    }
    
    func presentAlertError(response: ComicDetailScene.AlertError.Response) {
        viewController?.displayAlertError(viewModel: ComicDetailScene.AlertError.ViewModel(
            message: response.error.localizedDescription
        ))
    }

}
