//
//  ComicListPresenter.swift
//  marvelMovies
//
//  Created by Franco Marquez on 28/08/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the StartApps CleanSwift Xcode Templates. V2.0
//  By Gabriel Lanata (http://StartApps.pe) with credit to http://clean-swift.com
//

import Foundation

class ComicListPresenter {

    weak var viewController: ComicListViewController?

    // MARK: - Presentation logic
    
    func presentInitialComicListDataLoad(response: ComicListScene.InitialComicListDataLoad.Response) {
        // NOTE: Format the response from the Interactor and pass the result back to the View Controller
        // NOTE: Remember to use workers if complex processing is required
        
        var comicList = [ComicListScene.InitialComicListDataLoad.ViewModel.Comics]()
        
        for comic in response.comicsResponse.data.results{
            
            guard let url = URL(string: comic.thumbnail.path + "." + comic.thumbnail.thumbnailExtension.rawValue) else { continue }
            
            comicList.append(ComicListScene.InitialComicListDataLoad.ViewModel.Comics(comicName: comic.title,
                                                                                      comicPhotoURL: url,
                                                                                      comicID: comic.id))
            
        }
        
        viewController?.displayInitialComicListDataLoad(viewModel: ComicListScene.InitialComicListDataLoad.ViewModel.ComicList(comics: comicList))
        
    }
    
    func presentAlertError(response: ComicListScene.AlertError.Response) {
        viewController?.displayAlertError(viewModel: ComicListScene.AlertError.ViewModel(
            message: response.error.localizedDescription
        ))
    }

}
