//
//  ComicListModels.swift
//  marvelMovies
//
//  Created by Franco Marquez on 28/08/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the StartApps CleanSwift Xcode Templates. V2.0
//  By Gabriel Lanata (http://StartApps.pe) with credit to http://clean-swift.com
//

import Foundation

enum ComicListScene {
    
    enum InitialComicListDataLoad {
        
        struct Request {
        }
        struct Response {
            
            let comicsResponse: ComicsResponse
            
        }
        struct ViewModel {
            
            struct ComicList{
                let comics: [Comics]
            }
            
            struct Comics{
                let comicName: String
                let comicPhotoURL: URL
                let comicID: Int
            }
            
        }
        
    }
    
    enum AlertError {
        
        struct Response {
            let error: Error
        }
        struct ViewModel {
            let message: String
        }
        
    }

}
